export type Props {
    USE_TAGS: boolean;
    USE_ACTIONS: boolean;
    UPDATE_INTERVAL: number;
    PROCESS_SPEED: number;
    HEATER_LEVEL_SPEED: number;
    WATER_LEVEL_SPEED: number;
    VALVE_CHANGE_SPEED: number;
    STEAM_VALVE_CHANGE_SPEED: number;
    SOLVENT_FLOW: number;
    STEAM_FLOW: number;
    COOLING_FLOW: number;
    WATER_FLOW: number;
    WaterAlarm: boolean;
    HeaterAlarm: boolean;
    ProcessCounter: number;
    heater_high: number;
    heater_low: number;
    water_high: number;
    water_low: number;
    steam_high: number;
    steam_low: number;
    cooling_high: number;
    cooling_low: number;
    SolventValve: number;
    SteamValve: number;
    CoolingValve: number;
    WaterValve: number;
    SteamFlow: number;
    CoolingFlow: number;
    WaterFlow: number;
    OutFlow: number;
    HeaterTemperature: number;
    SteamTemperature: number;
    BeforePreHeaterTemperature: number;
    PreHeaterTemperature: number;
    AfterPreHeaterTemperature: number;
    CoolingTemperature: number;
    HeaterPressure: number;
    HeaterLevel: number;
    WaterLevel: number;
    GLG: any;
    CoordScale: number;
    viewport: any;
    timer: NodeJS.Timeout | null;
    timer_3D: NodeJS.Timeout | null;
}
